### PR TITLE
Make it a little easier to set up PhpStorm

### PR DESCRIPTION
**Pull request by murrant**
I was trying out PhpStorm (I'd like to use the refactoring and completion).  I think this will make it easier for others.

### CODE REVIEW

**Comment by laf** [comment]
Whilst I'm not against this (used to use phpstorm), where do we draw the line in adding support for varying IDE's? I'm currently using Atom but have used phpstorm, sublime and even tried visual studio!

**Comment by murrant** [comment]
That's a good question.  That is why I made the PR.  I'm fine with adding .idea to the .gitignore.  But I went through things and set up code style, copyright templates, phpunit, and runners.

I'll just stash this for now and send a simple PR

**Comment by f0o** [comment]
Speaking of IDE, any suggestions for a Linux user?

**Comment by murrant** [comment]
@f0o I am a Linux user, I know PhpStorm and Sublime Text both work on Linux, looks like Atom Editor as well (which I'm not personally familiar with).  I'm starting with PhpStorm as I'm familiar with IntelliJ IDEs already.

PhpStorm is more of a full IDE, the other two are text editors with really great functionality approaching an IDE.  For example, PhpStorm supports refactoring (renaming or moving things including classes and namespaces with a few keystrokes) the text editors support that only via plugins (which may not support the full range of refactoring options)

**Pull request closed without merging**
